### DISCUSSION TITLE
Basic installation under WSL/Ubuntu 20.04  with spack

### DISCUSSION THREAD

**Discussion by timofeymukha** [ExtremeFLOW/neko#496] [Show and tell]
I've just successfully installed neko using a fresh Ubuntu 20.04 running under WLS in Windows 10. I used spack, and this was my first time using the software, so I'm creating this post to potentially save some people time. I still have a remaining issue with `makeneko` though, for which I would like some help.

- Beforehand, install the following stuff with apt: `patchelf gcc gfortran g++ make`
- I also threw in a `miniconda` for a decent Python, no extra packages. But not sure if it is needed.
- Clone spack: `git clone https://github.com/spack/spack.git ~/spack`. Stay on the develop branch!
- cd to `spack` and activate some shell commands with `. spack/share/spack/setup-env.sh`
- At this point, do something like `spack install zlib`. This installs a small package, just to test that things work.
- Spack will automatically pickup the gcc you installed. But for some reason for me `g++` was not picked up. The compiler configuration is in a file here: `~/.spack/linux/compilers.yaml`. I added the path to `g++` to the `cxx` value. The configuration now looks like this.
````
compilers:
- compiler:
    spec: gcc@9.4.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
````
- Run `spack install neko@develop` to install from the develop branch. This will take a while, but will eventually install everything, including blas and openmpi.
- The actuall installation path is pretty obscrue, in my case `~/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/neko-develop-c3nrh6ntqvd3turc2utwpjwujbz6lxay/`
- The good thing is that you don't need to add all of this to the PATH yourself, instead run `spack load neko`.
- Done! You should have `neko` as an executable command now, as wells as `mpirun`.
